### ISSUE TITLE
(Subtask 4) Improve and refactor Direct / Indirect analyses

### ISSUE THREAD

**Issue by Carsopre** [Deltares/ra2ce#298]
- [x] #310
  - [x] #315 
  - [x] (Implicit in subtasks) Type hints and documentation when possible.
  - [x] We no longer use dictionaries but rather the new `AnalysisConfigData` protocols.
  - [x] **Extra** (related to refactoring direct / indirect) improve Single Responsibility Principle in all modules.
  - [x] (Implicit in subtasks) Tests should be updated accordingly.
  - [x] #312
  - [ ] #318
  - [ ] #349
  - [ ] Improve `analysis_factory` (different methods, new class for config needed to create analysis)
    - [ ] #348
  - [ ] #351

**Comment by Carsopre** [comment]
Addition:
- Keep extending the list of enums and replace their usage whenever possible. Example given, `loss_type`.

**Comment by ArdtK** [comment]
Open items are put in separate subtasks to be picked up later
